### ISSUE TITLE
Google Play Services 9.8.0 issue

### ISSUE THREAD

**Issue by espinosaluis** [dandar3/android-google-play-services-README#2]
dandar3,

I'm trying to install the latest libraries and I'm getting this error:
`Project 'android-google-play-services-maps' is missing required source folder: 'gen'`

I'm installing this on a new Windows installation, running Eclipse Neon, so maybe I'm forgetting something.

This is how my SDKs look like:
![capture](https://cloud.githubusercontent.com/assets/12634078/19829336/a6e9c14a-9dab-11e6-9ff7-6645098fa7e1.PNG)

Note that I don't have anything installed under "Extras" but I think nothing is needed based on your requirements.

Please let me know if you see something I may be missing.

Thanks.

**Comment by dandar3** [comment]
`gen` is a source folder that is normally created by the ADT plugin - it's where it generates sources like `BuildConfig.java` and `R.java`. That is a folder that is normally not uploaded into a source control repository.

See if `Project` > `Build automatically` is checked or do a `Project` > `Clean` > `Clean all projects` followed by a rebuild.

**Comment by espinosaluis** [comment]
Yeah, I have tried that. I did some research and it says it could be because of missing libraries and it's not compiling correctly.

**Comment by dandar3** [comment]
As long as the `Errors` section still shows error messages saying `gen` I would try to clear them out first. I would start closing all projects from the top of the depedency tree, and start rebuilding the bottom ones one by one. For example `android-support-media-compat` is a good start, solve its `gen` related error and then work away from there.

If you need some assistance fire me an email (email address in my profile) and I can join you in a TeamViewer session.

**Comment by espinosaluis** [comment]
I ended up installing Eclipse Juno instead. Neon was kind of slow to load for my computer.
Now everything works fine, so it must be some settings related to that new version.

Did you create those packages using Neon?

**Comment by dandar3** [comment]
I would check if the two Eclipse installations have the same ADT version. You can also start them with `-clean` parameter or add it to `eclipse.ini` (and remove it later) maybe that would help (clean plugin caches). 

Yes, I use Eclipse Neon v4.6.1 with ADT v23.0.7.2120684.  Sometimes you have to clean some of the projects twice or restart Eclipse for ADT plugin to initialize correctly (it's what well written unfortunatelly).

But there's nothing in the projects that should make them behave differently - you can pick any of the projects, see the Commits tab and click a commit to see what has changed from a previous version. Or you can compare two tags, see this link - https://help.github.com/articles/comparing-commits-across-time/

Good to hear you're back working now.

**Comment by espinosaluis** [comment]
Thanks, dandar3. I will keep those hints in mind for the future. I appreciate your help. 

Regards
