### ISSUE TITLE
Support android google play service for fitness

### ISSUE THREAD

**Issue by michaelDnguyen** [dandar3/android-google-play-services-README#3]
Hi dandar3,  
Are you provide a library to serve google fitness ? Or you can guide me how to convert library from Eclipse library project based:
ANDROID_SDK/extras/google/m2repository/com/google/android/gms/play-services-fitness/play-services-fitness-10.0.0.aar
Thanks & Best regard.

**Comment by dandar3** [comment]
@michaelDnguyen 
I can look into making `play-services-fitness` - I see it depends on mostly existing projects and `play-services-location` which would be new.

I wrote a Groovy script that I use with Jenkins so things are mostly automated, but if you want to try things yourself see this link to give you an idea on what to do: https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html

**Comment by michaelDnguyen** [comment]
Things that you mentioned are sufficient for me.
Thanks a lot for interest.

**Comment by dandar3** [comment]
`play-services-fitness` and `play-services-location` are now available, let me know if any problems.
https://github.com/dandar3/android-google-play-services-README/tree/10.0.0
